In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [3]:
np.random.seed(1)
np.random.binomial(1000, 0.5)

496

Supongamos que se lanzan dos dados justos
$$\Omega=\{1,2,3,4,5,6\}\times \{1,2,3,4,5,6\}$$

In [7]:
import itertools
from itertools import product

Omega= set(product({1,2,3,4,5,6}, repeat=2))
Omega
print(f"La cardinalidad del espacio muestral es: {len(Omega)}")

La cardinalidad del espacio muestral es: 36

vamos a consideerar el evento
$$S=\{(i,j)\in\ Omega:i+j=7\}$$

In [15]:
S= {om for om in Omega if (om[0]+om[1])==7}
S

{(1, 6), (2, 5), (3, 4), (4, 3), (5, 2), (6, 1)}

In [8]:
S={omega for omega in Omega}

Las tuplas son objetos que se escriben:
$$(x_1,x_2,x_3,....,x_n)$$

In [9]:
type((1,2))

tuple

In [10]:
(1,2)[0]

1

In [11]:
(1,2)[1]

2

In [35]:
from fractions import Fraction
def P(A, Omega):
  p=Fraction(len(A), len(Omega))
  return p

In [20]:
def S(n):
  S={om for om in Omega if (om[0]+om[1])==n}
  return S

In [21]:
for i in range(2,13):
  print(S(i))

{(1, 1)}
{(1, 2), (2, 1)}
{(3, 1), (1, 3), (2, 2)}
{(2, 3), (3, 2), (4, 1), (1, 4)}
{(2, 4), (1, 5), (5, 1), (4, 2), (3, 3)}
{(3, 4), (4, 3), (6, 1), (1, 6), (2, 5), (5, 2)}
{(4, 4), (6, 2), (2, 6), (5, 3), (3, 5)}
{(4, 5), (5, 4), (6, 3), (3, 6)}
{(4, 6), (6, 4), (5, 5)}
{(5, 6), (6, 5)}
{(6, 6)}

##Diccionario

In [23]:
estudiantes ={"Kevin": np.random.binomial(100,0.6,10),
              "Juan": np.random.binomial(100,0.6,10),
              "Marina": np.random.binomial(100,0.6,10),
              "Alvaro": np.random.binomial(100,0.6,10),
              "Roberto": np.random.binomial(100,0.6,10),
              "Ceci": np.random.binomial(100,0.6,10),
              "Jaume" : np.random.binomial(100,0.6,10),
              "Marifer" : np.random.binomial(100,0.6,10),
              "Godo": np.random.binomial(100,0.6,10)}
estudiantes

{'Kevin': array([56, 55, 60, 60, 58, 62, 54, 54, 61, 55]),
 'Juan': array([52, 56, 60, 56, 62, 67, 56, 62, 63, 60]),
 'Marina': array([54, 61, 70, 68, 68, 63, 53, 57, 53, 56]),
 'Alvaro': array([63, 54, 63, 62, 69, 57, 66, 57, 55, 63]),
 'Roberto': array([62, 55, 59, 52, 65, 58, 62, 63, 54, 70]),
 'Ceci': array([69, 58, 60, 66, 65, 58, 66, 65, 53, 54]),
 'Jaume': array([60, 63, 52, 59, 61, 49, 57, 64, 59, 53]),
 'Marifer': array([63, 49, 63, 60, 55, 61, 67, 60, 52, 48]),
 'Godo': array([60, 56, 53, 57, 61, 63, 53, 61, 59, 66])}

In [25]:
import pandas as pd
index = [1,2,3,4,5,6,7,8,9,10]
df=pd.DataFrame(estudiantes)
df

   Kevin  Juan  Marina  Alvaro  Roberto  Ceci  Jaume  Marifer  Godo
0     56    52      54      63       62    69     60       63    60
1     55    56      61      54       55    58     63       49    56
2     60    60      70      63       59    60     52       63    53
3     60    56      68      62       52    66     59       60    57
4     58    62      68      69       65    65     61       55    61
5     62    67      63      57       58    58     49       61    63
6     54    56      53      66       62    66     57       67    53
7     54    62      57      57       63    65     64       60    61
8     61    63      53      55       54    53     59       52    59
9     55    60      56      63       70    54     53       48    66

In [27]:
df ["Kevin"][3]

60

In [29]:
df.iloc[2]["Kevin"]

60

In [36]:
dic={i:P(S(i),Omega) for i in range(2,13)}
dic

{2: Fraction(1, 36),
 3: Fraction(1, 18),
 4: Fraction(1, 12),
 5: Fraction(1, 9),
 6: Fraction(5, 36),
 7: Fraction(1, 6),
 8: Fraction(5, 36),
 9: Fraction(1, 9),
 10: Fraction(1, 12),
 11: Fraction(1, 18),
 12: Fraction(1, 36)}

In [37]:
df.describe()

,Kevin,Juan,Marina,Alvaro,Roberto,Ceci,Jaume,Marifer,Godo
count,10.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,57.500000,59.40000,60.300000,60.900000,60.000000,61.400000,57.700000,57.800000,58.900000
std,3.064129,4.40202,6.634087,4.931757,5.497474,5.541761,4.922736,6.442912,4.201851
min,54.000000,52.00000,53.000000,54.000000,52.000000,53.000000,49.000000,48.000000,53.000000
25%,55.000000,56.00000,54.500000,57.000000,55.750000,58.000000,54.000000,52.750000,56.250000
50%,57.000000,60.00000,59.000000,62.500000,60.500000,62.500000,59.000000,60.000000,59.500000
75%,60.000000,62.00000,66.750000,63.000000,62.750000,65.750000,60.750000,62.500000,61.000000
max,62.000000,67.00000,70.000000,69.000000,70.000000,69.000000,64.000000,67.000000,66.000000

In [38]:
df.iloc[7]

Kevin      54
Juan       62
Marina     57
Alvaro     57
Roberto    63
Ceci       65
Jaume      64
Marifer    60
Godo       61
Name: 7, dtype: int64

In [40]:
descriptive= df.describe()
descriptive

,Kevin,Juan,Marina,Alvaro,Roberto,Ceci,Jaume,Marifer,Godo
count,10.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,57.500000,59.40000,60.300000,60.900000,60.000000,61.400000,57.700000,57.800000,58.900000
std,3.064129,4.40202,6.634087,4.931757,5.497474,5.541761,4.922736,6.442912,4.201851
min,54.000000,52.00000,53.000000,54.000000,52.000000,53.000000,49.000000,48.000000,53.000000
25%,55.000000,56.00000,54.500000,57.000000,55.750000,58.000000,54.000000,52.750000,56.250000
50%,57.000000,60.00000,59.000000,62.500000,60.500000,62.500000,59.000000,60.000000,59.500000
75%,60.000000,62.00000,66.750000,63.000000,62.750000,65.750000,60.750000,62.500000,61.000000
max,62.000000,67.00000,70.000000,69.000000,70.000000,69.000000,64.000000,67.000000,66.000000

In [41]:
descriptive.iloc[7]

Kevin      62.0
Juan       67.0
Marina     70.0
Alvaro     69.0
Roberto    70.0
Ceci       69.0
Jaume      64.0
Marifer    67.0
Godo       66.0
Name: max, dtype: float64

In [42]:
descriptive.iloc[7].max()

70.0

In [43]:
np.random.choice(["Godo", "Ceci"])

'Ceci'